pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [
                    [credentialsId: '9c4a0738-2cf4-1111-b83c-11113dab6511', 
                url: 'https://github.com/username/repo']])
            }
        }
        stage("Build and test") {
            steps {
                sh 'python WebTest.py'
                }
                }
            
    }
    }
